name = "blog-backend"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# For Prisma to work
node_compat = true

[env.production]
name = "blog-backend"
workers_dev = true  # Change to false when using custom domain

[vars]
DATABASE_URL = "DATABASE_URL_PLACEHOLDER"